language: haskell
ghc:
  - "8.2.2"
notifications:
  email: false
install:
 - travis_retry cabal update
 - cabal install alex happy hspec	text scotty
before_script:
- cabal configure --enable-tests
- cabal build
script:
- cabal test --show-details=always --test-options="--color"
