language: haskell
cabal: "2.4"
ghc:
  - "8.6.5"
notifications:
  email: false
install:
 - travis_retry cabal update
 - cabal install alex happy hspec string-interpolate
before_script:
- cabal configure --enable-tests
- cabal build
script:
- cabal test --show-details=always --test-options="--color"
